config/routes.rb
Rails.application.routes.draw do
  root to: "inicio#index"
  mount RailsAdmin::Engine => '/site/admin', as: 'rails_admin'
  mount Rapidfire::Engine => "/enquete"
  mount Ckeditor::Engine => '/ckeditor'
  #administração
  namespace :admin do
      resources :categories
      resources :news
      resources :publishers
      resources :articles
      resources :galleries
      resources :news_comments
      resources :advertisements
      resources :events
      resources :videos
      resources :contacts
      resources :surveys
      resources :newsletters
      resources :short_urls
      devise_for :users, class_name: "Admin::User",controllers:{
                                                   sessions: 'admin/users/sessions',
                                                   registrations: 'admin/users/registrations',
                                                   passwords: 'admin/users/passwords',
                                                   omniauth_callbacks:'admin/users/omniauth_callbacks' 
  }
  end
  #inicio
  get "/inicio" => "inicio#index"
  #categoria
  get "/categoria/:categoria/:id", to: "categoria#index"
  get "/categoria/arquivos/:id", to: "categoria#index"
  #noticia
  get "/noticias" => "noticia#index"
  get "/noticia/:id" => "noticia#index"
  #artigo
  get "/artigo/:id" => "artigo#index"
  get "/artigo/autor/:id" => "artigo#index_autor"
  get "/galeria" => "galeria#index"
  #eventos
  get '/eventos' => 'evento#index'
  get '/evento/:id' => 'evento#index'
  #pesquisa
  get "/pesquisa" => "pesquisa#index"
  get "/pesquisa/ultimas_noticias" => "pesquisa#ultimas_noticias"
  get "/pesquisa/todas_as_noticias" => "pesquisa#todas_as_noticias"
  get "/pesquisa/mais_lidas" => "pesquisa#mais_lidas"
  get "/pesquisa/eventos" => "pesquisa#eventos"
  get "/pesquisa/videos" => "pesquisa#videos"
  #outros
  get "/sobre" => "sobre#index"
  get "/contato" => "contato#index"
  get "/videos" => "video#index"
  get "/boletim/:id" => "admin/newsletters#confirmar_inscricao"
  get 'whatsapp/ultima_noticia' => "whatsapp#ultima_noticia"
  get 'whatsapp/noticia/:id' => "whatsapp#noticia"
  #404
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ] 
end

app/models/admin/gallery.rb
class Admin::Gallery < ApplicationRecord
  has_many_attached :images #cloudinary + carrierwave
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  before_action :set_admin_gallery, only: [:show, :edit, :update, :destroy]

  # GET /admin/galleries
  # GET /admin/galleries.json
  def index
    @admin_galleries = Admin::Gallery.all
  end

  # GET /admin/galleries/1
  # GET /admin/galleries/1.json
  def show
  end

  # GET /admin/galleries/new
  def new
    @admin_gallery = Admin::Gallery.new
  end

  # GET /admin/galleries/1/edit
  def edit
  end

  # POST /admin/galleries
  # POST /admin/galleries.json
  def create
    @admin_gallery = Admin::Gallery.new(admin_gallery_params)

    respond_to do |format|
      if @admin_gallery.save
        format.html { redirect_to @admin_gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @admin_gallery }
      else
        format.html { render :new }
        format.json { render json: @admin_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/galleries/1
  # PATCH/PUT /admin/galleries/1.json
  def update
    respond_to do |format|
      if @admin_gallery.update(admin_gallery_params)
        format.html { redirect_to @admin_gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_gallery }
      else
        format.html { render :edit }
        format.json { render json: @admin_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/galleries/1
  # DELETE /admin/galleries/1.json
  def destroy
    @admin_gallery.destroy
    respond_to do |format|
      format.html { redirect_to admin_galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_gallery
      @admin_gallery = Admin::Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_gallery_params
      params.fetch(:admin_gallery, {})
    end
end

app/views/admin/galleries/_form.html.erb
<%= form_with(model: admin_gallery, local: true) do |form| %>
  <% if admin_gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_gallery.errors.count, "error") %> prohibited this admin_gallery from being saved:</h2>

      <ul>
      <% admin_gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<h1>Editing Admin Gallery</h1>

<%= render 'form', admin_gallery: @admin_gallery %>

<%= link_to 'Show', @admin_gallery %> |
<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Galleries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_galleries.each do |admin_gallery| %>
      <tr>
        <td><%= link_to 'Show', admin_gallery %></td>
        <td><%= link_to 'Edit', edit_admin_gallery_path(admin_gallery) %></td>
        <td><%= link_to 'Destroy', admin_gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Gallery', new_admin_gallery_path %>

app/views/admin/galleries/new.html.erb
<h1>New Admin Gallery</h1>

<%= render 'form', admin_gallery: @admin_gallery %>

<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_gallery_path(@admin_gallery) %> |
<%= link_to 'Back', admin_galleries_path %>