config/routes.rb
Rails.application.routes.draw do
  root to: "inicio#index"
  mount RailsAdmin::Engine => '/site/admin', as: 'rails_admin'
  mount Rapidfire::Engine => "/enquete"
  mount Ckeditor::Engine => '/ckeditor'
  #administração
  namespace :admin do
      resources :categories
      resources :news
      resources :publishers
      resources :articles
      resources :galleries
      resources :news_comments
      resources :advertisements
      resources :events
      resources :videos
      resources :contacts
      resources :surveys
      resources :newsletters
      resources :short_urls
      devise_for :users, class_name: "Admin::User",controllers:{
                                                   sessions: 'admin/users/sessions',
                                                   registrations: 'admin/users/registrations',
                                                   passwords: 'admin/users/passwords',
                                                   omniauth_callbacks:'admin/users/omniauth_callbacks' 
  }
  end
  #inicio
  get "/inicio" => "inicio#index"
  #categoria
  get "/categoria/:categoria/:id", to: "categoria#index"
  get "/categoria/arquivos/:id", to: "categoria#index"
  #noticia
  get "/noticias" => "noticia#index"
  get "/noticia/:id" => "noticia#index"
  #artigo
  get "/artigo/:id" => "artigo#index"
  get "/artigo/autor/:id" => "artigo#index_autor"
  get "/galeria" => "galeria#index"
  #eventos
  get '/eventos' => 'evento#index'
  get '/evento/:id' => 'evento#index'
  #pesquisa
  get "/pesquisa" => "pesquisa#index"
  get "/pesquisa/ultimas_noticias" => "pesquisa#ultimas_noticias"
  get "/pesquisa/todas_as_noticias" => "pesquisa#todas_as_noticias"
  get "/pesquisa/mais_lidas" => "pesquisa#mais_lidas"
  get "/pesquisa/eventos" => "pesquisa#eventos"
  get "/pesquisa/videos" => "pesquisa#videos"
  #outros
  get "/sobre" => "sobre#index"
  get "/contato" => "contato#index"
  get "/videos" => "video#index"
  get "/boletim/:id" => "admin/newsletters#confirmar_inscricao"
  get 'whatsapp/ultima_noticia' => "whatsapp#ultima_noticia"
  get 'whatsapp/noticia/:id' => "whatsapp#noticia"
  #404
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ] 
end

app/models/admin/survey.rb
class Admin::Survey < ApplicationRecord
  before_create :only_one_row?

  default_scope {where(active: true)}
  def only_one_row?
    if (Admin::Survey.count == 1)
        errors.add(:base, "Só é Permitido um Unico Texto")
        raise ActiveRecord::RecordInvalid.new(self)
    end
  end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < ApplicationController
  before_action :set_admin_survey, only: [:show, :edit, :update, :destroy]

  # GET /admin/surveys
  # GET /admin/surveys.json
  def index
    @admin_surveys = Admin::Survey.all
  end

  # GET /admin/surveys/1
  # GET /admin/surveys/1.json
  def show
  end

  # GET /admin/surveys/new
  def new
    @admin_survey = Admin::Survey.new
  end

  # GET /admin/surveys/1/edit
  def edit
  end

  # POST /admin/surveys
  # POST /admin/surveys.json
  def create
    @admin_survey = Admin::Survey.new(admin_survey_params)

    respond_to do |format|
      if @admin_survey.save
        format.html { redirect_to @admin_survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @admin_survey }
      else
        format.html { render :new }
        format.json { render json: @admin_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/surveys/1
  # PATCH/PUT /admin/surveys/1.json
  def update
    respond_to do |format|
      if @admin_survey.update(admin_survey_params)
        format.html { redirect_to @admin_survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_survey }
      else
        format.html { render :edit }
        format.json { render json: @admin_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/surveys/1
  # DELETE /admin/surveys/1.json
  def destroy
    @admin_survey.destroy
    respond_to do |format|
      format.html { redirect_to admin_surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_survey
      @admin_survey = Admin::Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_survey_params
      params.require(:admin_survey).permit(:title, :survey_id, :active)
    end
end

app/controllers/rapidfire/surveys_controller.rb
module Rapidfire
  class SurveysController < Rapidfire::ApplicationController
    if Rails::VERSION::MAJOR == 5
      before_action :authenticate_administrator!, except: :index
    else
      before_filter :authenticate_administrator!, except: :index
    end

    def index
      @surveys = if defined?(Kaminari)
        Survey.page(params[:page])
      else
        Survey.all
      end
    end

    def new
      @survey = Survey.new
    end

    def create
      @survey = Survey.new(survey_params)
      if @survey.save
        respond_to do |format|
          format.html { redirect_to surveys_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render :new }
          format.js
        end
      end
    end

    def edit
      @survey = Survey.find(params[:id])
    end

    def update
      @survey = Survey.find(params[:id])
      if @survey.update(survey_params)
        respond_to do |format|
          format.html { redirect_to surveys_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.js
        end
      end
    end

    def destroy
      @survey = Survey.find(params[:id])
      @survey.destroy

      respond_to do |format|
        format.html { redirect_to surveys_path }
        format.js
      end
    end

    def results
      @survey = Survey.find(params[:id])
      @survey_results =
        SurveyResults.new(survey: @survey).extract

      respond_to do |format|
        format.json { render json: @survey_results, root: false }
        format.html
        format.js
      end
    end

    private

    def survey_params
      if Rails::VERSION::MAJOR >= 4
        params.require(:survey).permit(:name, :introduction, :after_survey_content)
      else
        params[:survey]
      end
    end
  end
end

app/helpers/admin/surveys_helper.rb
module Admin::SurveysHelper
end

app/views/admin/surveys/_form.html.erb
<%= form_with(model: admin_survey, local: true) do |form| %>
  <% if admin_survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_survey.errors.count, "error") %> prohibited this admin_survey from being saved:</h2>

      <ul>
      <% admin_survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :survey_id %>
    <%= form.number_field :survey_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/surveys/edit.html.erb
<h1>Editing Admin Survey</h1>

<%= render 'form', admin_survey: @admin_survey %>

<%= link_to 'Show', @admin_survey %> |
<%= link_to 'Back', admin_surveys_path %>

app/views/admin/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Survey</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_surveys.each do |admin_survey| %>
      <tr>
        <td><%= admin_survey.title %></td>
        <td><%= admin_survey.survey_id %></td>
        <td><%= admin_survey.active %></td>
        <td><%= link_to 'Show', admin_survey %></td>
        <td><%= link_to 'Edit', edit_admin_survey_path(admin_survey) %></td>
        <td><%= link_to 'Destroy', admin_survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Survey', new_admin_survey_path %>

app/views/admin/surveys/new.html.erb
<h1>New Admin Survey</h1>

<%= render 'form', admin_survey: @admin_survey %>

<%= link_to 'Back', admin_surveys_path %>

app/views/admin/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_survey.title %>
</p>

<p>
  <strong>Survey:</strong>
  <%= @admin_survey.survey_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @admin_survey.active %>
</p>

<%= link_to 'Edit', edit_admin_survey_path(@admin_survey) %> |
<%= link_to 'Back', admin_surveys_path %>