config/routes.rb
Rails.application.routes.draw do
  root to: "inicio#index"
  mount RailsAdmin::Engine => '/site/admin', as: 'rails_admin'
  mount Rapidfire::Engine => "/enquete"
  mount Ckeditor::Engine => '/ckeditor'
  #administração
  namespace :admin do
      resources :categories
      resources :news
      resources :publishers
      resources :articles
      resources :galleries
      resources :news_comments
      resources :advertisements
      resources :events
      resources :videos
      resources :contacts
      resources :surveys
      resources :newsletters
      resources :short_urls
      devise_for :users, class_name: "Admin::User",controllers:{
                                                   sessions: 'admin/users/sessions',
                                                   registrations: 'admin/users/registrations',
                                                   passwords: 'admin/users/passwords',
                                                   omniauth_callbacks:'admin/users/omniauth_callbacks' 
  }
  end
  #inicio
  get "/inicio" => "inicio#index"
  #categoria
  get "/categoria/:categoria/:id", to: "categoria#index"
  get "/categoria/arquivos/:id", to: "categoria#index"
  #noticia
  get "/noticias" => "noticia#index"
  get "/noticia/:id" => "noticia#index"
  #artigo
  get "/artigo/:id" => "artigo#index"
  get "/artigo/autor/:id" => "artigo#index_autor"
  get "/galeria" => "galeria#index"
  #eventos
  get '/eventos' => 'evento#index'
  get '/evento/:id' => 'evento#index'
  #pesquisa
  get "/pesquisa" => "pesquisa#index"
  get "/pesquisa/ultimas_noticias" => "pesquisa#ultimas_noticias"
  get "/pesquisa/todas_as_noticias" => "pesquisa#todas_as_noticias"
  get "/pesquisa/mais_lidas" => "pesquisa#mais_lidas"
  get "/pesquisa/eventos" => "pesquisa#eventos"
  get "/pesquisa/videos" => "pesquisa#videos"
  #outros
  get "/sobre" => "sobre#index"
  get "/contato" => "contato#index"
  get "/videos" => "video#index"
  get "/boletim/:id" => "admin/newsletters#confirmar_inscricao"
  get 'whatsapp/ultima_noticia' => "whatsapp#ultima_noticia"
  get 'whatsapp/noticia/:id' => "whatsapp#noticia"
  #404
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ] 
end

app/models/admin/event.rb
class Admin::Event < ApplicationRecord
    has_many_attached :images #cloudinary + carrierwave
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_admin_event, only: [:show, :edit, :update, :destroy]

  # GET /admin/events
  # GET /admin/events.json
  def index
    @admin_events = Admin::Event.all
  end

  # GET /admin/events/1
  # GET /admin/events/1.json
  def show
  end

  # GET /admin/events/new
  def new
    @admin_event = Admin::Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events
  # POST /admin/events.json
  def create
    @admin_event = Admin::Event.new(admin_event_params)

    respond_to do |format|
      if @admin_event.save
        format.html { redirect_to @admin_event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @admin_event }
      else
        format.html { render :new }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/events/1
  # PATCH/PUT /admin/events/1.json
  def update
    respond_to do |format|
      if @admin_event.update(admin_event_params)
        format.html { redirect_to @admin_event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_event }
      else
        format.html { render :edit }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1
  # DELETE /admin/events/1.json
  def destroy
    @admin_event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @admin_event = Admin::Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_event_params
      params.require(:admin_event).permit(:index)
    end
end

app/views/admin/events/_form.html.erb
<%= form_with(model: admin_event, local: true) do |form| %>
  <% if admin_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_event.errors.count, "error") %> prohibited this admin_event from being saved:</h2>

      <ul>
      <% admin_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing Admin Event</h1>

<%= render 'form', admin_event: @admin_event %>

<%= link_to 'Show', @admin_event %> |
<%= link_to 'Back', admin_events_path %>

app/views/admin/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Events</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_events.each do |admin_event| %>
      <tr>
        <td><%= admin_event.index %></td>
        <td><%= link_to 'Show', admin_event %></td>
        <td><%= link_to 'Edit', edit_admin_event_path(admin_event) %></td>
        <td><%= link_to 'Destroy', admin_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Event', new_admin_event_path %>

app/views/admin/events/new.html.erb
<h1>New Admin Event</h1>

<%= render 'form', admin_event: @admin_event %>

<%= link_to 'Back', admin_events_path %>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @admin_event.index %>
</p>

<%= link_to 'Edit', edit_admin_event_path(@admin_event) %> |
<%= link_to 'Back', admin_events_path %>