config/routes.rb
Rails.application.routes.draw do
  root to: "inicio#index"
  mount RailsAdmin::Engine => '/site/admin', as: 'rails_admin'
  mount Rapidfire::Engine => "/enquete"
  mount Ckeditor::Engine => '/ckeditor'
  #administração
  namespace :admin do
      resources :categories
      resources :news
      resources :publishers
      resources :articles
      resources :galleries
      resources :news_comments
      resources :advertisements
      resources :events
      resources :videos
      resources :contacts
      resources :surveys
      resources :newsletters
      resources :short_urls
      devise_for :users, class_name: "Admin::User",controllers:{
                                                   sessions: 'admin/users/sessions',
                                                   registrations: 'admin/users/registrations',
                                                   passwords: 'admin/users/passwords',
                                                   omniauth_callbacks:'admin/users/omniauth_callbacks' 
  }
  end
  #inicio
  get "/inicio" => "inicio#index"
  #categoria
  get "/categoria/:categoria/:id", to: "categoria#index"
  get "/categoria/arquivos/:id", to: "categoria#index"
  #noticia
  get "/noticias" => "noticia#index"
  get "/noticia/:id" => "noticia#index"
  #artigo
  get "/artigo/:id" => "artigo#index"
  get "/artigo/autor/:id" => "artigo#index_autor"
  get "/galeria" => "galeria#index"
  #eventos
  get '/eventos' => 'evento#index'
  get '/evento/:id' => 'evento#index'
  #pesquisa
  get "/pesquisa" => "pesquisa#index"
  get "/pesquisa/ultimas_noticias" => "pesquisa#ultimas_noticias"
  get "/pesquisa/todas_as_noticias" => "pesquisa#todas_as_noticias"
  get "/pesquisa/mais_lidas" => "pesquisa#mais_lidas"
  get "/pesquisa/eventos" => "pesquisa#eventos"
  get "/pesquisa/videos" => "pesquisa#videos"
  #outros
  get "/sobre" => "sobre#index"
  get "/contato" => "contato#index"
  get "/videos" => "video#index"
  get "/boletim/:id" => "admin/newsletters#confirmar_inscricao"
  get 'whatsapp/ultima_noticia' => "whatsapp#ultima_noticia"
  get 'whatsapp/noticia/:id' => "whatsapp#noticia"
  #404
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ] 
end

app/models/admin/newsletter.rb
class Admin::Newsletter < ApplicationRecord
    after_create :send_mail
    private
    def send_mail
      NewsletterMailer.with(mail: self).newsletter.deliver_now!
    end
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < ApplicationController
  before_action :set_admin_newsletter, only: [:show, :edit, :update, :destroy]

  def index
    @admin_newsletters = Admin::Newsletter.all
  end


  # def show
  # end


  def new
    @admin_newsletter = Admin::Newsletter.new
  end


  # def edit
  # end


  def create
    if params[:admin_newsletter][:mail].blank?
      msg = {:erro => "Oops! Alguma coisa aconteceu e não podemos confirmar sua inscrição."}
      flash[:newsletter_confirmation] = msg
      redirect_to root_path
      return
    end
    @admin_newsletter = Admin::Newsletter.new(admin_newsletter_params)
    @admin_newsletter.confirmation_id = ApplicationHelper.newsletter_confirmacao_id
    respond_to do |format|
      if @admin_newsletter.save
        flash[:newsletter] = 'Enviamos um e-mail de confirmacao para você.'
        format.html { redirect_to root_path }
        #format.json { render :show, status: :created, location: @admin_newsletter }
      else
        format.html { render :new }
        #format.json { render json: @admin_newsletter.errors, status: :unprocessable_entity }
      end
    end
  end


  # def update
  #   respond_to do |format|
  #     if @admin_newsletter.update(admin_newsletter_params)
  #       format.html { redirect_to @admin_newsletter, notice: 'Newsletter was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @admin_newsletter }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @admin_newsletter.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  # def destroy
  #   @admin_newsletter.destroy
  #   respond_to do |format|
  #     format.html { redirect_to admin_newsletters_url, notice: 'Newsletter was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def confirmar_inscricao
    id = params.permit("id")["id"]
    boletim = Admin::Newsletter.where(confirmation_status: nil,confirmation_id: id).first
    flash[:newsletter_confirmation] = []
    if not boletim.nil?
      boletim.confirmation_status = true
      boletim.save
      msg = {:sucesso => "Obrigado por confirmar sua inscrição no nosso boletim! Você recberá toda semana nosso boletim em seu e-mail."}
    else
      msg = {:erro => "Oops! Alguma coisa aconteceu e não podemos confirmar sua inscrição."}
    end
    flash[:newsletter_confirmation] = msg
    redirect_to root_path
    return
  end

  private

    def set_admin_newsletter
      @admin_newsletter = Admin::Newsletter.find(params[:id])
    end


    def admin_newsletter_params
      params.require(:admin_newsletter).permit(:mail)
    end
end

app/helpers/admin/newsletters_helper.rb
module Admin::NewslettersHelper
end

app/views/admin/newsletters/_form.html.erb
<%= form_with(model: admin_newsletter, local: true) do |form| %>
  <% if admin_newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_newsletter.errors.count, "error") %> prohibited this admin_newsletter from being saved:</h2>

      <ul>
      <% admin_newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/newsletters/edit.html.erb
<h1>Editing Admin Newsletter</h1>

<%= render 'form', admin_newsletter: @admin_newsletter %>

<%= link_to 'Show', @admin_newsletter %> |
<%= link_to 'Back', admin_newsletters_path %>

app/views/admin/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_newsletters.each do |admin_newsletter| %>
      <tr>
        <td><%= admin_newsletter.mail %></td>
        <td><%= link_to 'Show', admin_newsletter %></td>
        <td><%= link_to 'Edit', edit_admin_newsletter_path(admin_newsletter) %></td>
        <td><%= link_to 'Destroy', admin_newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Newsletter', new_admin_newsletter_path %>

app/views/admin/newsletters/new.html.erb
<h1>New Admin Newsletter</h1>

<%= render 'form', admin_newsletter: @admin_newsletter %>

<%= link_to 'Back', admin_newsletters_path %>

app/views/admin/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mail:</strong>
  <%= @admin_newsletter.mail %>
</p>

<%= link_to 'Edit', edit_admin_newsletter_path(@admin_newsletter) %> |
<%= link_to 'Back', admin_newsletters_path %>